version: '3'

services:
 db:
  image: florrdz/jsp-mysql
  container_name: jsp_mysql_contenedor 
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 'root'
   MYSQL_DATABASE: 'appjsp'
  ports:
   - '3306:3306'
 web:
  image: florrdz/jsp-tomcat
  container_name: jsp_tomcat_contenedor
  restart: always
  ports:
   - "8080:8080"