version: '3'

services:
 db:
  image: florrdz/crud-mysql
  container_name: crud_mysql_contenedor 
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 'root'
   MYSQL_DATABASE: 'servlet'
  ports:
   - '3306:3306'
 web:
  image: florrdz/crud-tomcat
  container_name: crud_tomcat_contenedor
  restart: always
  ports:
   - "8080:8080"